---
title: "TSIR"
date: "`r format(Sys.time(), '%H:%M %d %B %Y ')`"
author: Michael Li
---

## Problem

I am trying to figure out why the hybrid TSIR chain binomial is overshooting the estimates (See [poster](https://github.com/wzmli/lunchbox/blob/master/EEID_Final_Mike.pdf). If it doesn't work, just refresh the page.). Let's step through it starting from the very beginning.


## Discrete Latent State TSIR Chain Binomial

### Model

The Reed-Frost model is a discrete-time SIR model that assumes recovery one time step after infection. Let $N$ be the population size, $I_{1}$ be the initial number of infectives, $\beta$ be the probability of adequate contact per infective, then the RF model can be written as:

$$
S_{1} = N - I_{1}
\\
I_{t} \sim \textrm{Binomial}(\textrm{prob} = 1-(1-\beta)^{I_{t-1}} , \textrm{size}=S_{t-1})
\\
S_{t} = S_{t-1} - I_{t}
$$

We modified the RF model as a _latent_ binomial process and added an observation process with reporting probability $r$ and assumed $N_{e}$ is from an effective population with an effective proportion $\alpha$ of the upper limit population size _N_. The modified RF model can be written as:

$$
N_{e} \sim \textrm{Binomial}(\textrm{prob} = \alpha, \textrm{size}=N)
\\
S_{1} = N_{e} - I_{1}
\\
I_{t} \sim \textrm{Binomial}(\textrm{prob} = 1-(1-\beta)^{I_{t-1}} , \textrm{size}=S_{t-1})
\\
Obs_{t} \sim \textrm{Binomial}(\textrm{prob}=r,\textrm{size}=I_{t})
\\
S_{t} = S_{t-1} - I_{t}
$$

## Jags Discrete Latent State Model Results 
Using the same parameters as the models in the poster, here are the plots/chains for the discrete latent state chain binomial. _Note_ I used stronger priors for the poster and uninformative priors _Beta(1,1)_ for $\alpha$ and $r$. I also used the _true_ parameters as the initial starting point to see if we can even estimate the parameters given we have a good starting point.

###Parameters
- $R_{0} = 2$
- $\beta = 0.7 , \textrm{(effective proportion of population)}$
- $r = 0.4 , \textrm{(reporting mean/probability)}$

The codes are here (todo: change parameter names to be consistent with write-up):

- [Simulator](https://github.com/wzmli/lunchbox/blob/master/simulators/simulator.CB.R)
- [Bugs script](https://github.com/wzmli/lunchbox/blob/master/dis.B.B.buggen)
- [Parameters](https://github.com/wzmli/lunchbox/blob/master/parameters.CBB.R)
- [Run Jags](https://github.com/wzmli/lunchbox/blob/master/Jags.CB.R)


#### Instructions to reproduce the plots above
- **clone/pull** the latest version of [lunchbox](https://github.com/wzmli/lunchbox)
- type **make** (the first time will clone JD's makestuff)
- type **make** (the second time will simulate and fit the model)


```{r,echo=FALSE,warning=FALSE,message=FALSE}
library(R2jags)
load("./lunchbox/.dis.jags.B.B.fit.RData")
JagsDiscrete
plot(JagsDiscrete)
traceplot(JagsDiscrete,mfrow=c(2,2))
```
We can see clearly from the traceplots _r_ is not mixing well.

## Hybrid model

The orginal idea of hybridization was to improve the mixing for _r_ with some sort of **Scaling trick/ cliff**. We later realized we can take this even furtherand use a more powerful MCMC algorithm (Hamiltonian Monte Carlo). For now, let's try to figure out the problem in **JAGS**  

First we want to change the discrete latent process to continuous by setting the first and second moment (moment-matching (MM)) of the binomial distribution to a continuous distribution (ie. gamma in this case) and observation process to a poisson process (more detail on why possion). 
\\
_... skip all the moment-matching algebra ..._ 
\\
We can rewrite the model (todo: reference equation/system of equations?)  as:

$$
N_{e} \sim \textrm{Binomial}(\alpha,N)
\\
S_{1} = N_{e} - I_{1}
\\
I_{t} \sim \textrm{Gamma}(\textrm{shape} = \textrm{prob}\times S_{t-1} \times \textrm{rate}, \textrm{rate}= \frac{1}{1-\textrm{prob}})
\\
Obs_{t} \sim \textrm{Poisson}(\textrm{mean}=r \times I_{t})
\\
S_{t} = S_{t-1} - I_{t}
$$

## JAGS Hybrid Model Results

The codes are here (fake place holders):

- [Bugs script](https://github.com/wzmli/lunchbox/blob/master/dis.B.B.buggen)
- [Run Jags](https://github.com/wzmli/lunchbox/blob/master/Jags.CB.R)




